const game = {
  player: [
    {
      name: "🧝 Elf Knight",
      health: 30,
      maxHealth: 30,
      pointsId: "player",
      healthbarId: "player",
      hardAttackDamage: 4,
      hardAttackDice: 8,
      weakAttackDamage: 2,
      weakAttackDice: 3,
      attacks: [
        [
          "Shield Bash",
          2,
          3,
          "🛡️ You are trying to bash the opponent away with your shield ...",
          "💫 The enemy dodges your attack ...",
        ],
        [
          "Mace Attack",
          6,
          6,
          "🔨 You are trying hit the enemy with a huge mace ...",
          "💫 The enemy dodges your attack ...",
        ],
        [
          "Magic Attack",
          1,
          4,
          "🌀 You are trying to cast a spell on your opponent ...",
          "💫 The enemy dodges your attack ...",
        ],
      ],
    },
    {
      name: "🤖 Jones Verr",
      health: 30,
      maxHealth: 30,
      pointsId: "player",
      healthbarId: "player",
      hardAttackDamage: 4,
      hardAttackDice: 8,
      weakAttackDamage: 2,
      weakAttackDice: 3,
      attacks: [
        [
          "Shield Bash",
          2,
          3,
          "🛡️ You are trying to bash the opponent away with your shield ...",
          "💫 The enemy dodges your attack ...",
        ],
        [
          "Mace Attack",
          6,
          6,
          "🔨 You are trying hit the enemy with a huge mace ...",
          "💫 The enemy dodges your attack ...",
        ],
        [
          "Magic Attack",
          1,
          4,
          "🌀 You are trying to cast a spell on your opponent ...",
          "💫 The enemy dodges your attack ...",
        ],
      ],
    },
  ],
  enemy: [
    {
      name: "👾 Goblin Warrior",
      health: 12,
      maxHealth: 12,
      pointsId: "enemy",
      healthbarId: "enemy",
      hardAttackDamage: 6,
      hardAttackDice: 8,
      weakAttackDamage: 3,
      weakAttackDice: 4,
    },
    {
      name: "👽 Cuuwing",
      health: 12,
      maxHealth: 12,
      pointsId: "enemy",
      healthbarId: "enemy",
      hardAttackDamage: 4,
      hardAttackDice: 8,
      weakAttackDamage: 2,
      weakAttackDice: 3,
    },
    {
      name: "🥷 Wispfree Jones ",
      health: 12,
      maxHealth: 12,
      pointsId: "enemy",
      healthbarId: "enemy",
      hardAttackDamage: 4,
      hardAttackDice: 8,
      weakAttackDamage: 2,
      weakAttackDice: 3,
    },
    {
      name: "🧛 Break Gett",
      health: 15,
      maxHealth: 16,
      pointsId: "enemy",
      healthbarId: "enemy",
      hardAttackDamage: 4,
      hardAttackDice: 8,
      weakAttackDamage: 4,
      weakAttackDice: 4,
    },
  ],
};
